In [1]:
import numpy as np

In [2]:
a=np.array([2,3,4])

In [3]:
a

array([2, 3, 4])

In [4]:
type(a)


numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
a.ndim

1

In [9]:
b= np.array([[1,2,3],[4,5,6]])


In [10]:
b.shape


(2, 3)

In [11]:
type(b)

numpy.ndarray

In [12]:
b.dtype

dtype('int64')

In [13]:
b.size

6

In [14]:
b.nbytes

48

In [15]:



# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Array:")
print(arr)

# Shape of the array
print("Shape:", arr.shape)

# Number of dimensions
print("Dimensions:", arr.ndim)

# Basic operations
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))

Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Sum: 21
Mean: 3.5
Max: 6
